resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/6.yaml

packages:
- .

extra-deps:
- git: https://github.com/flipstone/flipstone-prelude.git
  commit: b516a71f960149ff6cec163e2ee0c61478e913e0
- higher-leveldb-0.6.0.0@sha256:e763c909464b566dcfa9f09683585e2c3fe49c3842539bb9180333d937b60ebd,2126

allow-newer: true
