resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/6.yaml

packages:
- .

extra-deps:
- git: https://github.com/flipstone/flipstone-prelude.git
  commit: 208bc1a01df26e62a2222e2dbe8b18b6d8e5e672
